version: 2

models:
  - name: stg_departments
    description: "Staged department data with proper types"
    columns:
      - name: department_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: department_name
        description: "Name of the department"
      - name: budget_amount
        description: "Annual budget allocation"
      - name: fiscal_year
        description: "Fiscal year for the budget"

  - name: stg_expenditures
    description: "Staged expenditure data with proper types"
    columns:
      - name: expenditure_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: department_id
        description: "Foreign key to departments"
        data_tests:
          - relationships:
              arguments:
                to: ref('stg_departments')
                field: department_id
      - name: amount
        description: "Expenditure amount"
      - name: category
        description: "Expenditure category"
      - name: expenditure_date
        description: "Date of expenditure"
